### ISSUE TITLE
Save package as manifest file issue

### ISSUE THREAD

**Issue by DavidSpackman** [erdomke/InnovatorAdmin#1]
When saving a package as a manifest, data can be truncated at the end of the file.

Example:
Export the part itemtype from a database and save as a manifest
Tested on 10SP5 OOTS database

![partitemtypeissue](https://cloud.githubusercontent.com/assets/5021654/8225418/ab45e73a-15d7-11e5-94e9-237c3c2589f5.png)

**Comment by erdomke** [comment]
This should be fixed in commit https://github.com/erdomke/InnovatorAdmin/commit/263ae19ce216fcb3c68b2d6cd165d892f8d3ee79. If not for some reason, let me know.
