### ISSUE TITLE
InnovatorAdmin does not start after last update

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#104]
After  updating to 2016.01.04.1942, and restarting, the application does not start.
Removing the app-2016.xxxx folder and starting the app from 2015.12.30.0937 brings up the message "no updates available".
Even downloading the latest release and reinstalling results in a non-working application.

**Comment by rneuber1** [comment]
I cleaned everythng and tried a fresh install:
Setup.exe installs into %LOCALAPPDATA%\InnovatorAdmin\app-2016.01.04.1942 but this application does not run. I do not have a run.bat anymore.

Setup.msi does not install anything at all.

**Comment by erdomke** [comment]
That is weird. I published a new release which I am hoping will help.  It deployed without issue to my computer.  Please let me know if the problem persists for you.

**Comment by rneuber1** [comment]
Just wrote to you via slack. I downloaded today’s version and it still does not start.

\Ralf


Von: Eric Domke [mailto:notifications@github.com]
Gesendet: Dienstag, 5. Januar 2016 14:22
An: erdomke/InnovatorAdmin
Cc: Neubersch, Ralf
Betreff: Re: [InnovatorAdmin] InnovatorAdmin does not start after last update (#104)


That is weird. I published a new release which I am hoping will help. It deployed without issue to my computer. Please let me know if the problem persists for you.

—
Reply to this email directly or view it on GitHub<https://github.com/erdomke/InnovatorAdmin/issues/104#issuecomment-168996016>.

Experience the GETRAG History Web Special!
http://history.getrag.com<http://history.getrag.com/?lang=en>


________________________________

GETRAG FORD Transmissions GmbH
Firmensitz • Scarletallee 2 • 50735 Köln • Deutschland
Sitz der Gesellschaft: Köln • Registergericht Köln • HRB 34097
Geschäftsführung: Mihir Kotecha (CEO), José Ignacio Alonso, Didier Lexa, John McDonald, Susan Slaughter
Vorsitzender des Aufsichtsrats: Johannes-Jürgen Albus


Disclaimer:
Wie Sie wissen, können über das Internet versandte E-Mails unter fremden Namen erstellt oder manipuliert werden. Aus diesem Grund sind unsere per E-Mail verschickten Nachrichten grundsätzlich keine rechtsverbindlichen Willenserklärungen.
Der Inhalt dieser E-Mail ist vertraulich und ausschließlich für den bezeichneten Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat dieser E-Mail oder dessen Vertreter sein sollten, so beachten Sie bitte, dass jede Form der Kenntnisnahme, Veröffentlichung, Vervielfältigung oder Weitergabe des Inhalts dieser E-Mail unzulässig ist. Wir bitten Sie, sich in diesem Fall mit dem Absender der E-Mail in Verbindung zu setzen.

**Comment by rneuber1** [comment]
Hi Eric,
I managed to run it. I have to select „Run as administrator“, then it works…..

\Ralf


Von: Eric Domke [mailto:notifications@github.com]
Gesendet: Dienstag, 5. Januar 2016 14:22
An: erdomke/InnovatorAdmin
Cc: Neubersch, Ralf
Betreff: Re: [InnovatorAdmin] InnovatorAdmin does not start after last update (#104)


That is weird. I published a new release which I am hoping will help. It deployed without issue to my computer. Please let me know if the problem persists for you.

—
Reply to this email directly or view it on GitHub<https://github.com/erdomke/InnovatorAdmin/issues/104#issuecomment-168996016>.

Experience the GETRAG History Web Special!
http://history.getrag.com<http://history.getrag.com/?lang=en>


________________________________

GETRAG FORD Transmissions GmbH
Firmensitz • Scarletallee 2 • 50735 Köln • Deutschland
Sitz der Gesellschaft: Köln • Registergericht Köln • HRB 34097
Geschäftsführung: Mihir Kotecha (CEO), José Ignacio Alonso, Didier Lexa, John McDonald, Susan Slaughter
Vorsitzender des Aufsichtsrats: Johannes-Jürgen Albus


Disclaimer:
Wie Sie wissen, können über das Internet versandte E-Mails unter fremden Namen erstellt oder manipuliert werden. Aus diesem Grund sind unsere per E-Mail verschickten Nachrichten grundsätzlich keine rechtsverbindlichen Willenserklärungen.
Der Inhalt dieser E-Mail ist vertraulich und ausschließlich für den bezeichneten Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat dieser E-Mail oder dessen Vertreter sein sollten, so beachten Sie bitte, dass jede Form der Kenntnisnahme, Veröffentlichung, Vervielfältigung oder Weitergabe des Inhalts dieser E-Mail unzulässig ist. Wir bitten Sie, sich in diesem Fall mit dem Absender der E-Mail in Verbindung zu setzen.

**Comment by rneuber1** [comment]
Hi Eric,

I added a comment to #97, but I cannot reopen it. Could you please do this?

\Ralf


Von: Eric Domke [mailto:notifications@github.com]
Gesendet: Dienstag, 5. Januar 2016 14:22
An: erdomke/InnovatorAdmin
Cc: Neubersch, Ralf
Betreff: Re: [InnovatorAdmin] InnovatorAdmin does not start after last update (#104)


That is weird. I published a new release which I am hoping will help. It deployed without issue to my computer. Please let me know if the problem persists for you.

—
Reply to this email directly or view it on GitHub<https://github.com/erdomke/InnovatorAdmin/issues/104#issuecomment-168996016>.

Experience the GETRAG History Web Special!
http://history.getrag.com<http://history.getrag.com/?lang=en>


________________________________

GETRAG FORD Transmissions GmbH
Firmensitz • Scarletallee 2 • 50735 Köln • Deutschland
Sitz der Gesellschaft: Köln • Registergericht Köln • HRB 34097
Geschäftsführung: Mihir Kotecha (CEO), José Ignacio Alonso, Didier Lexa, John McDonald, Susan Slaughter
Vorsitzender des Aufsichtsrats: Johannes-Jürgen Albus


Disclaimer:
Wie Sie wissen, können über das Internet versandte E-Mails unter fremden Namen erstellt oder manipuliert werden. Aus diesem Grund sind unsere per E-Mail verschickten Nachrichten grundsätzlich keine rechtsverbindlichen Willenserklärungen.
Der Inhalt dieser E-Mail ist vertraulich und ausschließlich für den bezeichneten Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat dieser E-Mail oder dessen Vertreter sein sollten, so beachten Sie bitte, dass jede Form der Kenntnisnahme, Veröffentlichung, Vervielfältigung oder Weitergabe des Inhalts dieser E-Mail unzulässig ist. Wir bitten Sie, sich in diesem Fall mit dem Absender der E-Mail in Verbindung zu setzen.
