### ISSUE TITLE
Installer does not finish

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#119]
I installed InnovatorAdmin on a new machine where I am admin, but nothing seems to happen.
Tried it several times just to find a bunch of setup processes running:

![image](https://cloud.githubusercontent.com/assets/6908002/12222208/a4e7164a-b7b5-11e5-9c7d-e9ea3b0498de.png)

**Comment by rneuber1** [comment]
Even "run as admin" does not work.

**Comment by erdomke** [comment]
I wish I knew how best to troubleshoot that.  I have yet to have problems on a computer I have used with similar symptoms.  For what it is worth, Innovator Admin uses the [Squirrel](https://github.com/Squirrel/Squirrel.Windows) installer.  While a really quick Google search didn't provide any fruitful information, perhaps there is more information buried deeper in the site?

**Comment by rneuber1** [comment]
Obviously related to the virus scanner ( #140 ). This issue can be closed.
