### ISSUE TITLE
German keyboard does not allow all characters

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#123]
On a german keyboard, the "at" Sign (@) is on AltGr+Q, but this does not work in the AML Studio Editor.

**Comment by rneuber1** [comment]
Unbelievable,

this fix message reached me in the very same second where I sent out the pull request for my fix ;-)

\Ralf


Von: Eric Domke [mailto:notifications@github.com]
Gesendet: Dienstag, 12. Januar 2016 14:22
An: erdomke/InnovatorAdmin
Cc: Neubersch, Ralf
Betreff: Re: [InnovatorAdmin] German keyboard does not allow all characters (#123)


Closed #123<https://github.com/erdomke/InnovatorAdmin/issues/123> via 58c1b02<https://github.com/erdomke/InnovatorAdmin/commit/58c1b025dc57973ce8c56dceeab030d274158a95>.

—
Reply to this email directly or view it on GitHub<https://github.com/erdomke/InnovatorAdmin/issues/123#event-512373038>.

Experience the GETRAG History Web Special!
http://history.getrag.com<http://history.getrag.com/?lang=en>


________________________________

GETRAG FORD Transmissions GmbH
Firmensitz • Scarletallee 2 • 50735 Köln • Deutschland
Sitz der Gesellschaft: Köln • Registergericht Köln • HRB 34097
Geschäftsführung: Mihir Kotecha (CEO), José Ignacio Alonso, Didier Lexa, John McDonald, Susan Slaughter
Vorsitzender des Aufsichtsrats: Johannes-Jürgen Albus


Disclaimer:
Wie Sie wissen, können über das Internet versandte E-Mails unter fremden Namen erstellt oder manipuliert werden. Aus diesem Grund sind unsere per E-Mail verschickten Nachrichten grundsätzlich keine rechtsverbindlichen Willenserklärungen.
Der Inhalt dieser E-Mail ist vertraulich und ausschließlich für den bezeichneten Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat dieser E-Mail oder dessen Vertreter sein sollten, so beachten Sie bitte, dass jede Form der Kenntnisnahme, Veröffentlichung, Vervielfältigung oder Weitergabe des Inhalts dieser E-Mail unzulässig ist. Wir bitten Sie, sich in diesem Fall mit dem Absender der E-Mail in Verbindung zu setzen.

**Comment by erdomke** [comment]
Yeah, that was funny. I definitely learn something new every day.  I never
knew that the AltGr key worked that way.  I'll stay away from other bug
fixes for a while, so you should be safe ;).  Thanks again for the
continued help.
