### ISSUE TITLE
Timezones- annoyances and errors

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#128]
In the timezones list, some entries are duplicate, at least almost:

![image](https://cloud.githubusercontent.com/assets/6908002/12394221/cd7ed480-bdfa-11e5-84e6-ecc88f960a19.png)
Maybe you mean CET and CEST (Summer Time?)

In general it would be nice to have the timezones sorted by time and showing the UTC offset. 
The correct timezone name would be handy, too:

http://www.timeanddate.com/time/zones/

**Comment by erdomke** [comment]
I am limited to what Windows has stored in the registry regarding names.  With that said, I have switched this to use the name with features the UTC offset and the city names.  It is also now sorted by UTC offset.
