### ISSUE TITLE
Table View - Column setup

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#129]
For some reason, the column setup box show both "Modified on" and "Modified On":
![image](https://cloud.githubusercontent.com/assets/6908002/12394419/0170d54e-bdfc-11e5-8797-00e008cfe19b.png)

The table view for "modified_on" and "created_on" shows only the date in short format, without the time. The XML view contains full information. How do I show times in the table view and why are the "modified on" columns shown twice in the setup?

**Comment by erdomke** [comment]
I can't tell you why the two modified dates are there.  However, in the new release, you will be able to see the property name from this dialog which might shed light on the situation.  The date will now also show with the times.
