### ISSUE TITLE
AMLStudio: Add a TreeView as output

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#13]
Add a simple tree-view for nested structures, just showing the keyed names and item types etc. 
Add a context menu with "Copy ID" etc. to every item.
See #5 for details.

**Comment by erdomke** [comment]
I didn't add a separate tree view, but instead enhanced the output control to fold the XML in much the same way as the tree view you describe would.  I also added a context menu to the editor which includes a Copy ID entry.  If this is not sufficient for your use case, let me know.

**Comment by rneuber1** [comment]
Hi Eric,

thanks for implementing the changes, I'll have a look at them tomorrow.
At the moment I do not have a laptop suitable for development at home, but this will change in the near future, then I will start adding new features and fixing bugs myself.
I got lots of ideas for further improvements, hopefully we can get this tool to become the swiss army knife of Aras development ;-)

\Ralf
________________________________________

**Comment by erdomke** [comment]
That sounds like a great plan to me.  Thanks!
