### ISSUE TITLE
"Value cannot be NULL" error when using SOAP as connection type

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#135]
All fields are filled in, but a click on "Test" results in a "Value cannot be null" error:

![image](https://cloud.githubusercontent.com/assets/6908002/12448447/4af4ae9a-bf76-11e5-9fb8-c08b7067ec19.png)

**Comment by erdomke** [comment]
As an FYI, SOAP connections are intended for testing WSDL-based SOAP endpoints (e.g. much like [SoapUI](https://www.soapui.org/)).  Therefore, while the bug is now fixed, I am not sure it was doing exactly what you had in mind.
