### ISSUE TITLE
AMLStudio: Search in XML or table output

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#15]
Allow to search in all output panes (Ctrl+F, Find strings, regex, XPath(!!))

**Comment by erdomke** [comment]
An initial stab at search within the text panes is now implemented.  (Replace functionality is mocked up but not implemented.)  This functionality will need improvements but should accomplish the basics.  This was implemented in commit 9123222 which was release v2015.11.30.1747.
