### ISSUE TITLE
Compare versionable items

### ISSUE THREAD

**Issue by DavidSpackman** [erdomke/InnovatorAdmin#153]
Would be be possible to have a function to compare versionable items against the previous generation? (also would be cool if able to compare against how the versionable item looked at a specific date)

Methods could compare just the method_code property, other versionable items could be the whole item.

Was looking at recently modified items and wanted a method to quickly check the changes that have been made to methods

**Comment by DavidSpackman** [comment]
Compare feature in the grid is great

Can it also be added to this area to query previous versions by generation / time?

![image](https://cloud.githubusercontent.com/assets/5021654/13559274/6ebb7920-e466-11e5-98d2-d7baeb601bc6.png)

**Comment by erdomke** [comment]
An attempt at this is now in the committed code waiting for release.

**Comment by DavidSpackman** [comment]
Looks really good.
Cheers
