### ISSUE TITLE
AMLStudio: Invoke it via hotkey

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#17]
Allow AML Studio to be placed into the taskbar, so that it can be invoked by a hotkey

**Comment by erdomke** [comment]
AML Studio can now be invoked directly via a command line switch.  This powers the new Jump List support which should get you the effect you desire.  This was part of commit 9123222, release v2015.11.30.1747.

![amlstudiojumplist](https://cloud.githubusercontent.com/assets/4406364/11507454/15afb066-9822-11e5-89c1-9a962c2ccf9e.png)

**Comment by rneuber1** [comment]
This looks great, but I don't know how to get that working. Looking at the code I found the command line switch /amlstudio: (why the colon?), but I cannot get it to work together with the updater.
