### ISSUE TITLE
Unable to upload a file

### ISSUE THREAD

**Issue by MangeshK3007** [erdomke/InnovatorAdmin#181]
I am trying to upload a file using AML:

Here is my AML:

<AML>
<Item type="Document" action="add">
            <classification>Bill Submission</classification>
            <has_files>1</has_files>
            <Relationships>
                     <Item type="Document File" action="add">
                            <related_id>
                                 <Item type="File" action="add">
                                         <actual_data>Bill 1</actual_data>
                                         <actual_filename>G:\abc.docx</actual_filename>
                                  </Item>
                            </related_id>
                     </Item>
                  </Relationships>
 </Item>
</AML>

but not able to upload file.

**Comment by erdomke** [comment]
I'm closing this as a duplicate of #180 so that we can continue the conversation there.
