### ISSUE TITLE
Auto-complete less comfortable compared to AMLStudio 1.2.1

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#41]
In AMLStudio 1.2.1, the auto-complete feature would automatically add the `=""` to an attribute, the AMLStudio component of InnovatorAdmin does not.

Example:
if you type "condition" you get this suggestions:
![image](https://cloud.githubusercontent.com/assets/6908002/9111034/22007f84-3c43-11e5-8665-e4fea8011110.png)

upon pressing *Enter*, you get different results:

![image](https://cloud.githubusercontent.com/assets/6908002/9111068/7b009fe2-3c43-11e5-9ff4-bebbb1cbc6b9.png)

**Comment by erdomke** [comment]
This is resolved with the intellisense improvements in commit 9123222 that are part of the release v2015.11.30.1747.
