### ISSUE TITLE
Select the locale/culture for a connection

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#43]
The results of requests can differ depending on the regional or language settings of a user.
Add the possibility to choose the culture (nash offers this feature).
Technically, this means adding a HTTP-Header with name 'LOCALE' and value e.g. 'de-DE'

**Comment by erdomke** [comment]
This is implemented in commit 15752ab (release v2015.12.01.1139) in the Edit > Preferences menu.
