### ISSUE TITLE
Add an "explore" button to Connection Manager and AML Studio

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#48]
An "explore" button which opens the selected connection in the browser would be a nice to have feature:

![image](https://cloud.githubusercontent.com/assets/6908002/10440524/47ddf100-7140-11e5-8c33-a3cb9d81bd1c.png)

![image](https://cloud.githubusercontent.com/assets/6908002/10440543/80ef2112-7140-11e5-9b68-b2849a168d30.png)

Something like the code below, perhaps? (I'm still having problems with VS Design Editor, so no pull request from my side for this, yet). :weary:

```c#
 private void btnExplore_Click(object sender, EventArgs e)
    {
        try
        {
            lblMessage.Text = "Opening Browser...";
            Application.DoEvents();
            string arasUrl;
            ConnectionData cd = (ConnectionData)_bs.Current;

            arasUrl = cd.Url + "?database=" + cd.Database + "&username=" + cd.UserName + "&password=" + ConnectionData.ScalcMD5(cd.Password);
            System.Diagnostics.Process.Start(arasUrl);
            lblMessage.Text = "";
        }
        catch (Exception ex)
        {
            Utils.HandleError(ex);
        }
    }
```

**Comment by rneuber1** [comment]
Maybe we should add "?bypass_logon_form=1" to the URL. This will make IE login automatically.
And what about systems, where IE or (Firefox SE for newer Aras versions) is not the default browser!? ;-)

**Comment by DavidSpackman** [comment]
bypass_logon_form=1 didnt work for me
I had to change this to bypass_logon_form=true
