### ISSUE TITLE
stored Password not working anymore

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#49]
With the latest InnovatorAdmin version it reads the stored configuration, but does not recognize the passwords (Authentication failed). One has to reenter the PWs once for every connection.

**Comment by erdomke** [comment]
In order to support new authentication mechanisms, storing and using the MD5 hash of the password is no longer supported.  Since this was a part of the previous storage mechanism, there will be a one-time update required.  Sorry!
