### ISSUE TITLE
Layout problems when resizing the AML studio window

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#60]
The bottom line behaves weird when resizing the window:
![image](https://cloud.githubusercontent.com/assets/6908002/11530223/309b000c-98f3-11e5-8b8a-e8fe616d8493.png)
![image](https://cloud.githubusercontent.com/assets/6908002/11530224/341088ec-98f3-11e5-9712-4538c3423f51.png)
![image](https://cloud.githubusercontent.com/assets/6908002/11530226/377fe720-98f3-11e5-84a2-0cdccbc68c9a.png)

**Comment by erdomke** [comment]
I believe that this should be resolved with the latest release
