### ISSUE TITLE
Problem installing without elevated rights

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#64]
If a user has no admin rights, it is not possible to install InnovatorAdmin, not even via "Run as Administrator".
If it is installed as admin via "Run as", it gets installed into the %LOCALAPPDATA%" of the admin user.

**Comment by erdomke** [comment]
Do you have any additional information about what fails?  In the installer
itself is designed to not require any administration privileges.
Therefore, it might be something I am doing in the tool itself that is
causing the problems.

**Comment by rneuber1** [comment]
Might have do to with anti-virus issue #140 
Therefore this can be closed.
