### ISSUE TITLE
"Run current" does not work

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#66]
I have two statements within one AML clause and when I call "Run current", not the one with the caret or the selection is executed, but all (or the first?!) is excuted.

**Comment by erdomke** [comment]
The current intended operation of the latest version is as follows.  If additional scenarios need to be considered and/or supported, let me know.

Note that the `|` character is your cursor and the bold section is the selection.

# Situation 1: Two root-level code blocks

Using `Run Current` will execute the code block that the cursor is in (in this case, the second one).

<pre>
&lt;AML&gt;
  &lt;Item type='User' action='get'&gt;
    &lt;last_name&gt;Smith&lt;/last_name&gt;
  &lt;/Item&gt;
&lt;/AML&gt;
&lt;AML&gt;
  &lt;Item type='User' action='get'&gt;
    &lt;last_name&gt;<b>|</b>Domke&lt;/last_name&gt;
  &lt;/Item&gt;
&lt;/AML&gt;
</pre>

# Situation 2: One code block; multi-character selection

Using `Run Current` will treat the selection as your query and run it (in this case, only the first Item tag).

<pre>
&lt;AML&gt;
  <b>&lt;Item type='User' action='get'&gt;
    &lt;last_name&gt;Smith&lt;/last_name&gt;
  &lt;/Item&gt;|</b>
  &lt;Item type='User' action='get'&gt;
    &lt;last_name&gt;Domke&lt;/last_name&gt;
  &lt;/Item&gt;
&lt;/AML&gt;
</pre>

# Situation 3: One code block; no selection

Using `Run Current` can't find a "current" query and instead uses the entire document (both Item tags).

<pre>
&lt;AML&gt;
  &lt;Item type='User' action='get'&gt;
    &lt;last_name&gt;Smith&lt;/last_name&gt;
  &lt;/Item&gt;
  &lt;Item type='User' action='get'&gt;
    &lt;last_name&gt;<b>|</b>Domke&lt;/last_name&gt;
  &lt;/Item&gt;
&lt;/AML&gt;
</pre>

**Comment by rneuber1** [comment]
ok, in this case you may close this issue.
