### ISSUE TITLE
AML Studio: Submit into new tab

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#7]
It would be great to have a "Submit into new tab" button next to the "Submit" button. This should then open another tab in which there is the XML- and the Table View. These tabs could be colored according to the connection they came from. Add a tooltip to the tab for details.
See #5 for details.

**Comment by erdomke** [comment]
Because tab management is difficult to get right, the tool now implements the ability to run a query in a new window which should achieve a similar effect.  Each window is colored based on the connection.  This was implemented in commit 9123222 which was release v2015.11.30.1747.
