### ISSUE TITLE
Update stuck at 69%

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#74]
The update mechanism stops at 69%:

![image](https://cloud.githubusercontent.com/assets/6908002/11843310/43dd0c70-a409-11e5-9fb1-c952fcde73f1.png)

**Comment by rneuber1** [comment]
Maybe its a glitch somewhere, it counts:
33%, 43%, 33%, 41%,53%,64%, 69%

**Comment by erdomke** [comment]
I am trying to figure that out myself.  I ended up re-installing on my computer, but I will keep an eye on it with new releases.

**Comment by erdomke** [comment]
This appears to be fixed with the latest releases
