### ISSUE TITLE
Add Context actions to TOC items

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#75]
It would be nice to right-click on an itemtype in the TOC and get the actions "Get" and "Add" which would create the appropriate AML-Statement:
Example:
**CAD**->Right Mouse Click->Get adds `<Item type='CAD' action='get'></Item>`

![image](https://cloud.githubusercontent.com/assets/6908002/11844198/c4ff652e-a40d-11e5-825d-0adb738dd5b4.png)

And for a Relationship Element, it would add the complete Relationship Query:

![image](https://cloud.githubusercontent.com/assets/6908002/11844271/278d003e-a40e-11e5-8922-4fa9ed27fab6.png)

**Comment by erdomke** [comment]
Most of the way there.  I will have to think on the Relationship query idea.

**Comment by erdomke** [comment]
I think the modifying the current query with relationships will be too complex.  Therefore, I am going to close this given the current functionality for now.
