### ISSUE TITLE
Setting locale and timezone is gone

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#81]
Where have the settings for timezone and locale gone?
![image](https://cloud.githubusercontent.com/assets/6908002/11865003/5f138cc4-a4a1-11e5-9c7d-d7befe6557e6.png)

Or did you remove them from the preferences already in order to move them to the connection settings?
In this case (if the locale is selectable per connection), it would be great if the TOC came up with the localized labels!

**Comment by erdomke** [comment]
In the latest release, they should be under the Tools > Preferences menu.  I have not moved them under anything connection-specific yet.
