### ISSUE TITLE
Crash when running another instance

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#92]
It occured when starting another AMLStudio via the Shortcuts in the taskbar.

![image](https://cloud.githubusercontent.com/assets/6908002/11899582/27feaf70-a5a0-11e5-8d35-da97421a5698.png)

**Comment by rneuber1** [comment]
To reproduce: Start InnovatorAdmin, from there start an AMLStudio. Now open a different session via the shortcuts in the Taskbar.
It does not happen, if you start InnovatorAdmin with the command line switch /amlstudio:

**Comment by erdomke** [comment]
This should now be fixed with the latest release
