### ISSUE TITLE
Table view hides important columns

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#99]
With the recent release, the table view does not show all columns, eg. "config_id" is not visible anymore:

![image](https://cloud.githubusercontent.com/assets/6908002/12092034/04b2ef32-b2fb-11e5-90f0-0c1e7dc39934.png)

**Comment by erdomke** [comment]
As discussed in the linked issue #102, all columns are available for view via the right click > "Columns..." context menu item.
